apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: udagram-proxy
  name: udagram-proxy
spec:
  selector:
    matchLabels:
      app: udagram-proxy
  template:
    metadata:
      labels:
        app: udagram-proxy
    spec:
      containers:
        - name: udagram-proxy
          image: dragma/udagram-proxy:4.1
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
